### ISSUE TITLE
running preprocessing_mask file for final prostatex

### ISSUE THREAD

**Issue by tapan8455** [naimsassine/MasterThesisInfo2021#1]
Hey Naim,
I am trying to run preprocessing_masks.py from Final Preprocessing but I am getting the error below:
ImportError: cannot import name 'LsqEllipse' from 'ellipse'
I have tried all ways to resolve this issue, can I know which software did you use to run al your python files.

**Comment by naimsassine** [comment]
Hey! Did you already install the lsqellipse package? if not, you can do it using pip : pip install lsq-ellipse. It seems to me like an Import issue, so that package isn't downloaded or not located. Hope it helps!

**Comment by tapan8455** [comment]
I did try installing it and also upgraded the pip in pycharm, but it would still show that error and I also  have a error in LesionDetection.py file , you are loading train_images_concatenated file from google drive, so can you tell me in which python file you generated the npy file.

**Comment by naimsassine** [comment]
the train_images_concatenated is generated using the preprocessing functions. And for the package importing, I can't exactly tell you what's wrong since the package isn't being installed from your side : even if you try Importing the package in any python environment (outside of my project) does it work?

**Comment by tapan8455** [comment]
I tried running it in another file but it would generate the same error, Maybe the software compatibility is an issue.so if you can tell me which platform did you use to execute your codes would be wonderful .

**Comment by tapan8455** [comment]
> the train_images_concatenated is generated using the preprocessing functions. And for the package importing, I can't exactly tell you what's wrong since the package isn't being installed from your side : even if you try Importing the package in any python environment (outside of my project) does it work?

I also see that there is no main function in preprocessing_masks.py file, without it the code doesn't generate the desired output, kindly help me with it.
