### ISSUE TITLE
Problems encountered when reproducing the project

### ISSUE THREAD

**Issue by WindDream15** [naimsassine/MasterThesisInfo2021#3]
Hello Naim, 
After reading your paper and reproducing the project, I would like to ask you the following questions
 Firstly, in the configuration environment, I found that the package introduced in the code from metrics import dice_coef, dice_coef_loss does not exist. Is there any alias or need to introduce an external file? 
Secondly, There are two lines of code in the common_functions.py file that are causing errors. Specifically, line 260 with print('Accuracy:', dice_metric(y, y_pred)) and line 273 with surfd = surface_dist(y_true[i], y_pred[i], sampling=spacing). The error indicates that the parameters y and spacing in these two lines of code are unresolved reference.
 Finally,After reading your paper, I still don't understand how to operate the files in the project for model training and testing. Could you please provide further operational guidance?
The above are some of my questions.If you have the time to answer my question, I would greatly appreciate it.

**Comment by naimsassine** [comment]
Hello!
Thank you for your questions and thanks for checking out my work, i'll try to answer to the best of my abilities!
1. I honestly don't remember if I downloaded a certain library or if I wrote the functions by hand myself. But anyways, if you don't find any library that implements these functions, you can write them by hand (see screenshot)
<img width="702" alt="Screenshot 2024-08-21 at 22 12 40" src="https://github.com/user-attachments/assets/08680527-c200-4be6-9267-966d9473b377">

2. try to check if what you get in these variables is coherent. Are they empty? do they contain coherent values? 

3. What do you mean by operating the files? the MRI files? or the project coding files?

Hope this helps!

**Comment by WindDream15** [comment]
Thank you very much for your time to reply to me. Through your answers, the first two problems have been effectively solved. But for the third problem, there are many code files in the project, and most of them don't have main functions, so when I want to reproduce the project completely, I don't know the order of execution of these code files, and whether I need to change them, or write a separate code file to call its functions. And for the dataset, can I use the PROSTATEx challenge dataset and Promise12 dataset directly after selecting the appropriate format? Looking forward to your reply again.

**Comment by naimsassine** [comment]
Hello!
Sorry for taking some time to answer. But yes indeed I reviewed my code, i'm sorry it's not very clear which step goes first. It's been a while since I wrote it, so I don't recall all the details, but I think that I wrote in my pdf thesis which steps I used and in what order. Sorry to not be more helpful than this :(
